const ARMOR_DATABASE = [ 
{
    name: "Станционная одежда, полётная",
    type: "Лёгкая",
    lvl: 1,
    price: 95,
    eac: 0,
    kac: 1,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Эстексный комбинезон I",
    type: "Лёгкая",
    lvl: 1,
    price: 410,
    eac: 0,
    kac: 1,
    max_agi: 5,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "\’Вторая кожа\’",
    type: "Лёгкая",
    lvl: 1,
    price: 250,
    eac: 1,
    kac: 2,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Дифрактор Цейцерер I",
    type: "Лёгкая",
    lvl: 2,
    price: 650,
    eac: 2,
    kac: 2,
    max_agi: 4,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Касатский микрокордовый костюм I",
    type: "Лёгкая",
    lvl: 2,
    price: 460,
    eac: 1,
    kac: 3,
    max_agi: 3,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Броня \’Флибустьер\’ I",
    type: "Лёгкая",
    lvl: 2,
    price: 750,
    eac: 2,
    kac: 3,
    max_agi: 4,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Кожанная броня \’Скиттер\’ I",
    type: "Лёгкая",
    lvl: 3,
    price: 1200,
    eac: 2,
    kac: 3,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-03"
},
{
    name: "Композитная оболочка",
    type: "Лёгкая",
    lvl: 3,
    price: 1200,
    eac: 2,
    kac: 3,
    max_agi: 5,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Углеволоконная кожа \’Графит\’",
    type: "Лёгкая",
    lvl: 3,
    price: 1220,
    eac: 3,
    kac: 4,
    max_agi: 4,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Станционная одежда, повседневная",
    type: "Лёгкая",
    lvl: 3,
    price: 1300,
    eac: 1,
    kac: 2,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Лашунтский термокостюм, простой",
    type: "Лёгкая",
    lvl: 4,
    price: 1950,
    eac: 4,
    kac: 4,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Доспех из шкуры акрохора, простой",
    type: "Лёгкая",
    lvl: 4,
    price: 2100,
    eac: 5,
    kac: 5,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-04"
},
{
    name: "Броня из шкуры дефрекса",
    type: "Лёгкая",
    lvl: 4,
    price: 2250,
    eac: 5,
    kac: 5,
    max_agi: 4,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Станционная одежда, деловая",
    type: "Лёгкая",
    lvl: 5,
    price: 2600,
    eac: 2,
    kac: 3,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Эстексный комбинезон II",
    type: "Лёгкая",
    lvl: 5,
    price: 2700,
    eac: 4,
    kac: 5,
    max_agi: 5,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Т-костюм I",
    type: "Лёгкая",
    lvl: 5,
    price: 2980,
    eac: 5,
    kac: 6,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Касатский микрокордовый костюм II",
    type: "Лёгкая",
    lvl: 6,
    price: 3670,
    eac: 6,
    kac: 8,
    max_agi: 5,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Станционная одежда, высокачественная",
    type: "Лёгкая",
    lvl: 6,
    price: 4100,
    eac: 4,
    kac: 5,
    max_agi: 7,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Фольгированый комбинезон исоки",
    type: "Лёгкая",
    lvl: 6,
    price: 4120,
    eac: 7,
    kac: 7,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Дифрактор Цейцерер II",
    type: "Лёгкая",
    lvl: 6,
    price: 4150,
    eac: 6,
    kac: 6,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Броня \’Флибустьер\’ II",
    type: "Лёгкая",
    lvl: 6,
    price: 4720,
    eac: 6,
    kac: 8,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Эстексный комбинезон III",
    type: "Лёгкая",
    lvl: 7,
    price: 5500,
    eac: 7,
    kac: 8,
    max_agi: 5,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Т-костюм II",
    type: "Лёгкая",
    lvl: 7,
    price: 6900,
    eac: 8,
    kac: 9,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Деловой костюм корпорации \’Абадар\’ серебрянного класса",
    type: "Лёгкая",
    lvl: 7,
    price: 7250,
    eac: 6,
    kac: 7,
    max_agi: 7,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Броня спецназа ВГ",
    type: "Лёгкая",
    lvl: 7,
    price: 7500,
    eac: 7,
    kac: 8,
    max_agi: 5,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: "3 + 2 камня вечных",
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ИА-01"
},
{
    name: "Королевские боевые регалии Ацланти",
    type: "Лёгкая",
    lvl: 7,
    price: 8000,
    eac: 7,
    kac: 8,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "1",
    upgrades: "3 + 1 камень вечных",
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "Облачённое в броню существо получает +4 к проверкам Блефа, Дипломатии и запугивания против Ацланти.\nКаждый комплект оснащён предохранительным механизмом, который активируется один раз в день, когда у носителя брони остаётся 15 или менее ПЗ. При активации оно переносит носителя в представленное им место (аналогично эффект двери в пространстве).",
    source: "СП-09"
},
{
    name: "Доспех из шкуры акрохора, улучшенный",
    type: "Лёгкая",
    lvl: 8,
    price: 8250,
    eac: 10,
    kac: 10,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-04"
},
{
    name: "Лашунтский термокостюм, улучшенный",
    type: "Лёгкая",
    lvl: 8,
    price: 8500,
    eac: 9,
    kac: 10,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Касатский микрокордовый костюм III",
    type: "Лёгкая",
    lvl: 8,
    price: 9000,
    eac: 9,
    kac: 11,
    max_agi: 5,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Деловой костюм корпорации \’Абадар\’ золотого класса",
    type: "Лёгкая",
    lvl: 9,
    price: 12100,
    eac: 9,
    kac: 10,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Дифрактор Цейцерер III",
    type: "Лёгкая",
    lvl: 9,
    price: 12500,
    eac: 11,
    kac: 11,
    max_agi: 7,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Кожанная броня \’Скиттер\’ II",
    type: "Лёгкая",
    lvl: 9,
    price: 12500,
    eac: 10,
    kac: 11,
    max_agi: 7,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-03"
},
{
    name: "Т-костюм III",
    type: "Лёгкая",
    lvl: 9,
    price: 13300,
    eac: 11,
    kac: 12,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Броня \’Флибустьер\’ III",
    type: "Лёгкая",
    lvl: 10,
    price: 16900,
    eac: 12,
    kac: 13,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Углеволоконная кожа \’Карбин\’",
    type: "Лёгкая",
    lvl: 10,
    price: 19650,
    eac: 12,
    kac: 14,
    max_agi: 5,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Касатский микрокордовый костюм IV",
    type: "Лёгкая",
    lvl: 11,
    price: 23800,
    eac: 13,
    kac: 15,
    max_agi: 6,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Доспех из шкуры акрохора, улучшенный",
    type: "Лёгкая",
    lvl: 12,
    price: 28000,
    eac: 15,
    kac: 15,
    max_agi: 7,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-04"
},
{
    name: "Деловой костюм корпорации \’Абадар\’ платинового класса",
    type: "Лёгкая",
    lvl: 12,
    price: 30750,
    eac: 12,
    kac: 13,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Световая броня, стандартная",
    type: "Лёгкая",
    lvl: 12,
    price: 37500,
    eac: 15,
    kac: 15,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Т-костюм IV",
    type: "Лёгкая",
    lvl: 13,
    price: 45800,
    eac: 16,
    kac: 17,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Дифрактор Цейцерер IV",
    type: "Лёгкая",
    lvl: 13,
    price: 48500,
    eac: 15,
    kac: 15,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Эстексный комбинезон IV",
    type: "Лёгкая",
    lvl: 13,
    price: 49250,
    eac: 15,
    kac: 16,
    max_agi: 6,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Броня \’Флибустьер\’ IV",
    type: "Лёгкая",
    lvl: 14,
    price: 60600,
    eac: 17,
    kac: 18,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Костюм \’Эшелон\’ массового производства",
    type: "Лёгкая",
    lvl: 14,
    price: 71300,
    eac: 15,
    kac: 16,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Рой\’",
    type: "Лёгкая",
    lvl: 15,
    price: 95200,
    eac: 18,
    kac: 19,
    max_agi: 6,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Световая броня, элитная",
    type: "Лёгкая",
    lvl: 15,
    price: 123500,
    eac: 18,
    kac: 18,
    max_agi: 7,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Углеволоконная кожа \’Алмаз\’",
    type: "Лёгкая",
    lvl: 15,
    price: 126400,
    eac: 17,
    kac: 19,
    max_agi: 7,
    penalty: 1,
    speed: null,
    weight: "1",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Кожанная броня \’Скиттер\’ III",
    type: "Лёгкая",
    lvl: 16,
    price: 144000,
    eac: 19,
    kac: 19,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-03"
},
{
    name: "Броня шоталашу",
    type: "Лёгкая",
    lvl: 16,
    price: 149500,
    eac: 19,
    kac: 20,
    max_agi: 7,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Костюм \’Эшелон\’ индивидуального пошива",
    type: "Лёгкая",
    lvl: 17,
    price: 285000,
    eac: 18,
    kac: 19,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Дифрактор Цейцерер V",
    type: "Лёгкая",
    lvl: 18,
    price: 340000,
    eac: 20,
    kac: 20,
    max_agi: 9,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Броня \’Флибустьер\’ V",
    type: "Лёгкая",
    lvl: 18,
    price: 367650,
    eac: 20,
    kac: 21,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Т-костюм V",
    type: "Лёгкая",
    lvl: 18,
    price: 367650,
    eac: 20,
    kac: 21,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Т-костюм VI",
    type: "Лёгкая",
    lvl: 19,
    price: 552000,
    eac: 21,
    kac: 22,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Углеволоконная кожа \’Графен\’",
    type: "Лёгкая",
    lvl: 20,
    price: 825000,
    eac: 21,
    kac: 23,
    max_agi: 8,
    penalty: -1,
    speed: null,
    weight: "1",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Световая броня, специальная",
    type: "Лёгкая",
    lvl: 20,
    price: 928000,
    eac: 22,
    kac: 22,
    max_agi: 8,
    penalty: null,
    speed: null,
    weight: "Л",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Церемониальные латы, простые",
    type: "Тяжёлая",
    lvl: 1,
    price: 110,
    eac: 1,
    kac: 3,
    max_agi: 2,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Голем\’ I",
    type: "Тяжёлая",
    lvl: 1,
    price: 250,
    eac: 2,
    kac: 4,
    max_agi: 0,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Лашунтская \’Кольчуга\’ I",
    type: "Тяжёлая",
    lvl: 1,
    price: 415,
    eac: 2,
    kac: 4,
    max_agi: 2,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Безликий солдат\’",
    type: "Тяжёлая",
    lvl: 2,
    price: 465,
    eac: 3,
    kac: 5,
    max_agi: 2,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Иридий\’, простой",
    type: "Тяжёлая",
    lvl: 2,
    price: 755,
    eac: 3,
    kac: 6,
    max_agi: 2,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Кьёкор\’ I",
    type: "Тяжёлая",
    lvl: 2,
    price: 800,
    eac: 2,
    kac: 4,
    max_agi: 3,
    penalty: -1,
    speed: -5,
    weight: "1",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: null,
    source: null
},
{
    name: "Латы Рыцарей Преисподней \’Оруженосец\’",
    type: "Тяжёлая",
    lvl: 2,
    price: 980,
    eac: 4,
    kac: 5,
    max_agi: 2,
    penalty: -2,
    speed: -10,
    weight: "3",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "\’Тонкий панцирь\’",
    type: "Тяжёлая",
    lvl: 2,
    price: 1000,
    eac: 4,
    kac: 6,
    max_agi: 2,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Вызов\’, стандартный",
    type: "Тяжёлая",
    lvl: 3,
    price: 1220,
    eac: 5,
    kac: 8,
    max_agi: 1,
    penalty: -4,
    speed: -10,
    weight: "3",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Голем\’ II",
    type: "Тяжёлая",
    lvl: 3,
    price: 1610,
    eac: 5,
    kac: 7,
    max_agi: 2,
    penalty: -2,
    speed: -10,
    weight: "3",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Боевой костюм рядового ВГ",
    type: "Тяжёлая",
    lvl: 3,
    price: 1650,
    eac: 5,
    kac: 7,
    max_agi: 2,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: "1 + 1 камень вечных",
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ИА-01"
},
{
    name: "Церемониальные латы, офицерские",
    type: "Тяжёлая",
    lvl: 4,
    price: 2275,
    eac: 6,
    kac: 8,
    max_agi: 2,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Формианский панцирь, простой",
    type: "Тяжёлая",
    lvl: 4,
    price: 2400,
    eac: 7,
    kac: 8,
    max_agi: 2,
    penalty: -3,
    speed: -5,
    weight: "2",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "If you have the limited telepathy racial trait, you add 10 feet to the range of that ability. This increase doesn\’t stack with other effects that extend the range of your telepathy, such as a psychic booster.",
    source: "МС"
},
{
    name: "Лашунтская \’Кольчуга\’ II",
    type: "Тяжёлая",
    lvl: 5,
    price: 2970,
    eac: 8,
    kac: 10,
    max_agi: 2,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронелаты, простые",
    type: "Тяжёлая",
    lvl: 5,
    price: 3000,
    eac: 10,
    kac: 11,
    max_agi: 3,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-04"
},
{
    name: "Костяной покров I",
    type: "Тяжёлая",
    lvl: 5,
    price: 3100,
    eac: 9,
    kac: 9,
    max_agi: 2,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-03"
},
{
    name: "Латы Рыцарей Преисподней \’Ликтор\’",
    type: "Тяжёлая",
    lvl: 5,
    price: 3300,
    eac: 9,
    kac: 10,
    max_agi: 2,
    penalty: -2,
    speed: -10,
    weight: "3",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Вескарианская \’Сверхброня\’ I",
    type: "Тяжёлая",
    lvl: 6,
    price: 3910,
    eac: 9,
    kac: 11,
    max_agi: 3,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 1,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Кьёкор\’ II",
    type: "Тяжёлая",
    lvl: 6,
    price: 4820,
    eac: 8,
    kac: 10,
    max_agi: 4,
    penalty: -1,
    speed: -5,
    weight: "1",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: null,
    source: null
},
{
    name: "Бронекостюм \’Голем\’ III",
    type: "Тяжёлая",
    lvl: 7,
    price: 5500,
    eac: 10,
    kac: 12,
    max_agi: 3,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Формианский панцирь, улучшенный",
    type: "Тяжёлая",
    lvl: 7,
    price: 6100,
    eac: 10,
    kac: 12,
    max_agi: 3,
    penalty: -3,
    speed: -5,
    weight: "2",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "If you have the limited telepathy racial trait, you add 10 feet to the range of that ability. This increase doesn\’t stack with other effects that extend the range of your telepathy, such as a psychic booster.",
    source: "МС"
},
{
    name: "Бронекостюм \’Вызов\’, элитный",
    type: "Тяжёлая",
    lvl: 7,
    price: 6300,
    eac: 10,
    kac: 13,
    max_agi: 2,
    penalty: -4,
    speed: -10,
    weight: "3",
    upgrades: 2,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Церемониальные латы, командирские",
    type: "Тяжёлая",
    lvl: 7,
    price: 7350,
    eac: 10,
    kac: 12,
    max_agi: 2,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Лашунтская \’Кольчуга\’ III",
    type: "Тяжёлая",
    lvl: 8,
    price: 8420,
    eac: 12,
    kac: 14,
    max_agi: 3,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Вескарианская \’Сверхброня\’ II",
    type: "Тяжёлая",
    lvl: 8,
    price: 10250,
    eac: 13,
    kac: 15,
    max_agi: 2,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронелаты, улучшенные",
    type: "Тяжёлая",
    lvl: 9,
    price: 12000,
    eac: 15,
    kac: 16,
    max_agi: 3,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-04"
},
{
    name: "Бронекостюм \’Иридий\’, улучшенный",
    type: "Тяжёлая",
    lvl: 9,
    price: 13100,
    eac: 13,
    kac: 15,
    max_agi: 3,
    penalty: null,
    speed: null,
    weight: "2",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Легионерская броня \’Пиньон\’",
    type: "Тяжёлая",
    lvl: 9,
    price: 14200,
    eac: 14,
    kac: 16,
    max_agi: 3,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Латы Рыцарей Преисподней \’Мараликтор\’",
    type: "Тяжёлая",
    lvl: 9,
    price: 14500,
    eac: 16,
    kac: 17,
    max_agi: 2,
    penalty: -2,
    speed: -10,
    weight: "3",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Боевой косютом командира ВГ",
    type: "Тяжёлая",
    lvl: 10,
    price: 7500,
    eac: 15,
    kac: 17,
    max_agi: 3,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: "2 + 3 камня вечных",
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ИА-01"
},
{
    name: "Формианский панцирь, превосходный",
    type: "Тяжёлая",
    lvl: 10,
    price: 16500,
    eac: 15,
    kac: 17,
    max_agi: 3,
    penalty: -4,
    speed: -5,
    weight: "2",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "If you have the limited telepathy racial trait, you add 10 feet to the range of that ability. This increase doesn\’t stack with other effects that extend the range of your telepathy, such as a psychic booster.",
    source: "МС"
},
{
    name: "Бронекостюм \’Вызов\’, специальный",
    type: "Тяжёлая",
    lvl: 10,
    price: 16950,
    eac: 15,
    kac: 18,
    max_agi: 2,
    penalty: -4,
    speed: -10,
    weight: "3",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Кьёкор\’ III",
    type: "Тяжёлая",
    lvl: 10,
    price: 17100,
    eac: 13,
    kac: 16,
    max_agi: 4,
    penalty: -2,
    speed: -5,
    weight: "1",
    upgrades: 3,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: null,
    source: null
},
{
    name: "Вескарианская \’Сверхброня\’ III",
    type: "Тяжёлая",
    lvl: 11,
    price: 23400,
    eac: 16,
    kac: 18,
    max_agi: 3,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Голем\’ IV",
    type: "Тяжёлая",
    lvl: 11,
    price: 24800,
    eac: 15,
    kac: 17,
    max_agi: 3,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Лашунтская \’Кольчуга\’ IV",
    type: "Тяжёлая",
    lvl: 11,
    price: 27100,
    eac: 16,
    kac: 18,
    max_agi: 4,
    penalty: -3,
    speed: -5,
    weight: "2",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Вескарианский бронекостюм \’Монолит\’ I",
    type: "Тяжёлая",
    lvl: 12,
    price: 39650,
    eac: 16,
    kac: 18,
    max_agi: 4,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Иридий\’, превосходный",
    type: "Тяжёлая",
    lvl: 12,
    price: 42250,
    eac: 17,
    kac: 18,
    max_agi: 4,
    penalty: null,
    speed: null,
    weight: "2",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Эгида\’, стандартный",
    type: "Тяжёлая",
    lvl: 12,
    price: 45200,
    eac: 17,
    kac: 19,
    max_agi: 3,
    penalty: -5,
    speed: -10,
    weight: "3",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронелаты, элитные",
    type: "Тяжёлая",
    lvl: 13,
    price: 48000,
    eac: 19,
    kac: 20,
    max_agi: 4,
    penalty: -3,
    speed: -5,
    weight: "2",
    upgrades: 0,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-04"
},
{
    name: "Легионерская броня \’Экзидент\’",
    type: "Тяжёлая",
    lvl: 13,
    price: 53600,
    eac: 18,
    kac: 20,
    max_agi: 4,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Костяной покров II",
    type: "Тяжёлая",
    lvl: 13,
    price: 55000,
    eac: 19,
    kac: 19,
    max_agi: 4,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-03"
},
{
    name: "Бронекостюм \’Голем\’ V",
    type: "Тяжёлая",
    lvl: 14,
    price: 63750,
    eac: 18,
    kac: 20,
    max_agi: 4,
    penalty: -3,
    speed: -10,
    weight: "3",
    upgrades: 7,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Вескарианская \’Сверхброня\’ IV",
    type: "Тяжёлая",
    lvl: 14,
    price: 71850,
    eac: 19,
    kac: 21,
    max_agi: 4,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Кьёкор\’ IV",
    type: "Тяжёлая",
    lvl: 14,
    price: 76000,
    eac: 17,
    kac: 19,
    max_agi: 5,
    penalty: -2,
    speed: -5,
    weight: "1",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: null,
    source: null
},
{
    name: "Латы Рыцарей Преисподней \’Параликтор\’",
    type: "Тяжёлая",
    lvl: 14,
    price: 80000,
    eac: 21,
    kac: 22,
    max_agi: 3,
    penalty: -2,
    speed: -10,
    weight: "3",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "МС"
},
{
    name: "Лашунтская \’Кольчуга\’ V",
    type: "Тяжёлая",
    lvl: 15,
    price: 94200,
    eac: 20,
    kac: 22,
    max_agi: 4,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "\’Машинист\’",
    type: "Тяжёлая",
    lvl: 15,
    price: 120900,
    eac: 21,
    kac: 22,
    max_agi: 4,
    penalty: null,
    speed: null,
    weight: "2",
    upgrades: 5,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "\’Стальной костяк\’",
    type: "Тяжёлая",
    lvl: 16,
    price: 145500,
    eac: 21,
    kac: 23,
    max_agi: 4,
    penalty: -3,
    speed: -5,
    weight: "2",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Вескарианский бронекостюм \’Монолит\’ II",
    type: "Тяжёлая",
    lvl: 16,
    price: 163400,
    eac: 22,
    kac: 24,
    max_agi: 4,
    penalty: -3,
    speed: -5,
    weight: "2",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Эгида\’, элитный",
    type: "Тяжёлая",
    lvl: 17,
    price: 209000,
    eac: 23,
    kac: 27,
    max_agi: 3,
    penalty: -5,
    speed: -10,
    weight: "3",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Витрумные латы",
    type: "Тяжёлая",
    lvl: 18,
    price: 365650,
    eac: 23,
    kac: 24,
    max_agi: 5,
    penalty: null,
    speed: null,
    weight: "1",
    upgrades: 4,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Кьёкор\’ V",
    type: "Тяжёлая",
    lvl: 18,
    price: 371000,
    eac: 23,
    kac: 24,
    max_agi: 5,
    penalty: -2,
    speed: -5,
    weight: "1",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: null,
    source: null
},
{
    name: "Вескарианская \’Сверхброня\’ V",
    type: "Тяжёлая",
    lvl: 18,
    price: 415800,
    eac: 24,
    kac: 26,
    max_agi: 4,
    penalty: -3,
    speed: -5,
    weight: "2",
    upgrades: 7,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Войд\’",
    type: "Тяжёлая",
    lvl: 19,
    price: 610250,
    eac: 25,
    kac: 26,
    max_agi: 5,
    penalty: -3,
    speed: -5,
    weight: "2",
    upgrades: 7,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Костяной покров III",
    type: "Тяжёлая",
    lvl: 19,
    price: 645000,
    eac: 25,
    kac: 25,
    max_agi: 6,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 6,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "СП-03"
},
{
    name: "Вескарианский бронекостюм \’Монолит\’ III",
    type: "Тяжёлая",
    lvl: 20,
    price: 827250,
    eac: 26,
    kac: 27,
    max_agi: 5,
    penalty: -2,
    speed: -5,
    weight: "2",
    upgrades: 7,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Бронекостюм \’Эгида\’, специальный",
    type: "Тяжёлая",
    lvl: 20,
    price: 932000,
    eac: 25,
    kac: 28,
    max_agi: 4,
    penalty: -4,
    speed: -10,
    weight: "3",
    upgrades: 7,
    str: null,
    damage: null,
    size: null,
    capacity: null,
    usage: null,
    max_weapons: null,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Экзоскелет-погрузчик",
    type: "Силовая",
    lvl: 4,
    price: 2150,
    eac: +0,
    kac: 7,
    max_agi: 0,
    penalty: -10,
    speed: 15,
    weight: "34",
    upgrades: 0,
    str: "20 (+5)",
    damage: "1d10 Д",
    size: "Крупный",
    capacity: 40,
    usage: "1 в минуту",
    max_weapons: 0,
    additional_info: "-4 к проверкам атаки.\nПредельный вес увеличен на 10.",
    source: "ОКП"
},
{
    name: "Боевой экзокостюм",
    type: "Силовая",
    lvl: 5,
    price: 3450,
    eac: 9,
    kac: 12,
    max_agi: 2,
    penalty: -4,
    speed: 30,
    weight: "20",
    upgrades: 1,
    str: "18 (+4)",
    damage: "1d10 Д",
    size: "Средний",
    capacity: 20,
    usage: "1 в час",
    max_weapons: 1,
    additional_info: "-",
    source: "ОКП"
},
{
    name: "Экзокостюм \’Паук\’",
    type: "Силовая",
    lvl: 10,
    price: 19500,
    eac: 10,
    kac: 13,
    max_agi: 5,
    penalty: -4,
    speed: 25,
    weight: "28",
    upgrades: 2,
    str: "18 (+4)",
    damage: "1d10 Ко",
    size: "Крупный",
    capacity: 40,
    usage: "1 в минуту",
    max_weapons: 1,
    additional_info: "Лазание 25 футов",
    source: "ОКП"
},
{
    name: "Летающий экзокостюм",
    type: "Силовая",
    lvl: 11,
    price: 27100,
    eac: 12,
    kac: 19,
    max_agi: 3,
    penalty: -5,
    speed: 30,
    weight: "40",
    upgrades: 4,
    str: "22 (+6)",
    damage: "2d6 Д",
    size: "Огромный",
    capacity: 100,
    usage: "1 в минуту",
    max_weapons: 3,
    additional_info: "Полёт 30 футов (средняя манёвренность)",
    source: "ОКП"
},
{
    name: "Экзокостюм \’Ярлоборец\’",
    type: "Силовая",
    lvl: 15,
    price: 125500,
    eac: 18,
    kac: 24,
    max_agi: 4,
    penalty: -6,
    speed: 20,
    weight: "43",
    upgrades: 2,
    str: "29 (+9)",
    damage: "2d8 Д",
    size: "Крупный",
    capacity: 100,
    usage: "1 в минуту",
    max_weapons: 2,
    additional_info: "-",
    source: "ОКП"
}
];