const CLASS_DATABASE = [ 
{
    name: "Механик",
    skills_per_lvl: 4,
    hp_per_lvl: 6,
    sp_per_lvl: 6,
    BAB_per_lvl: 0.75,
    fort_base: 2,
    fort_per_lvl: 2,
    refl_base: 2,
    refl_per_lvl: 2,
    will_base: 0,
    will_per_lvl: 3,
    key_abiscore: "ИНТ",
    is_caster: false,
    armor_prof: "Лёгкая",
    weapon_prof: "Простое ближнего боя, Короткоствольное, Граната",
    class_skills: "Атлетика, Внимание, Инженерное дело, Компьютеры, Медицина, Пилотирование, Физические науки",
    source: "ОКП"
},
{
    name: "Мистик",
    skills_per_lvl: 6,
    hp_per_lvl: 6,
    sp_per_lvl: 6,
    BAB_per_lvl: 0.75,
    fort_base: 0,
    fort_per_lvl: 3,
    refl_base: 0,
    refl_per_lvl: 3,
    will_base: 2,
    will_per_lvl: 2,
    key_abiscore: "МДР",
    is_caster: true,
    armor_prof: "Лёгкая",
    weapon_prof: "Простое ближнего боя, Короткоствольное",
    class_skills: "Биологические науки, Блеф, Внимание, Выживание, Дипломатия, Запугивание, Культура, Маскировка, Медицина, Мистицизм, Проницательность",
    source: "ОКП"
},
{
    name: "Оперативник",
    skills_per_lvl: 8,
    hp_per_lvl: 6,
    sp_per_lvl: 6,
    BAB_per_lvl: 0.75,
    fort_base: 0,
    fort_per_lvl: 3,
    refl_base: 2,
    refl_per_lvl: 2,
    will_base: 2,
    will_per_lvl: 2,
    key_abiscore: "ЛВК",
    is_caster: false,
    armor_prof: "Лёгкая",
    weapon_prof: "Простое ближнего боя, Короткоствольное, Снайперское",
    class_skills: "Акробатика, Атлетика, Блеф, Внимание, Выживание, Запугивание, Инженерное дело, Компьютеры, Культура, Ловкость рук, Маскировка, Медицина, Пилотирование, Проницательность, Скрытность",
    source: "ОКП"
},
{
    name: "Посланник",
    skills_per_lvl: 8,
    hp_per_lvl: 6,
    sp_per_lvl: 6,
    BAB_per_lvl: 0.75,
    fort_base: 0,
    fort_per_lvl: 3,
    refl_base: 2,
    refl_per_lvl: 2,
    will_base: 2,
    will_per_lvl: 2,
    key_abiscore: "ХАР",
    is_caster: false,
    armor_prof: "Лёгкая",
    weapon_prof: "Простое ближнего боя, Короткоствольное, Граната",
    class_skills: "Акробатика, Атлетика, Блеф, Внимание, Дипломатия, Запугивание, Инженерное дело, Компьютеры, Культура, Ловкость рук, Маскировка, Медицина, Пилотирование, Проницательность, Скрытность",
    source: "ОКП"
},
{
    name: "Солдат",
    skills_per_lvl: 4,
    hp_per_lvl: 7,
    sp_per_lvl: 7,
    BAB_per_lvl: 1,
    fort_base: 2,
    fort_per_lvl: 2,
    refl_base: 0,
    refl_per_lvl: 3,
    will_base: 2,
    will_per_lvl: 2,
    key_abiscore: "СИЛ или ЛВК",
    is_caster: false,
    armor_prof: "Лёгкая, Тяжёлая",
    weapon_prof: "Простое ближнего боя, Высокотехнологичное ближнего боя, Короткоствольное, Длинноствольное, Снайперское, Тяжёлое, Граната",
    class_skills: "Акробатика, Атлетика, Выживание, Запугивание, Инженерное дело, Медицина, Пилотирование",
    source: "ОКП"
},
{
    name: "Солярион",
    skills_per_lvl: 4,
    hp_per_lvl: 7,
    sp_per_lvl: 7,
    BAB_per_lvl: 1,
    fort_base: 2,
    fort_per_lvl: 2,
    refl_base: 0,
    refl_per_lvl: 3,
    will_base: 2,
    will_per_lvl: 2,
    key_abiscore: "ХАР",
    is_caster: false,
    armor_prof: "Лёгкая",
    weapon_prof: "Простое ближнего боя, Высокотехнологичное ближнего боя, Короткоствольное",
    class_skills: "Акробатика, Атлетика, Внимание, Дипломатия, Запугивание, Мистицизм, Проницательность, Скрытность, Физические науки",
    source: "ОКП"
},
{
    name: "Техномант",
    skills_per_lvl: 4,
    hp_per_lvl: 5,
    sp_per_lvl: 5,
    BAB_per_lvl: 0.75,
    fort_base: 0,
    fort_per_lvl: 3,
    refl_base: 0,
    refl_per_lvl: 3,
    will_base: 2,
    will_per_lvl: 2,
    key_abiscore: "ИНТ",
    is_caster: true,
    armor_prof: "Лёгкая",
    weapon_prof: "Простое ближнего боя, Короткоствольное",
    class_skills: "Биологические науки, Инженерное дело, Компьютеры, Ловкость рук, Мистицизм, Пилотирование, Физические науки",
    source: "ОКП"
}
];